# Generated by Django 4.2.16 on 2025-05-15 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(help_text='Conteúdo do post')),
                ('media_file', models.CharField(blank=True, help_text='Arquivo de mídia opcional', max_length=255, null=True)),
                ('edited', models.BooleanField(default=False, help_text='Indica se o post foi editado')),
                ('edited_at', models.DateTimeField(blank=True, help_text='Data da última edição', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Indica se o post está visível')),
                ('author', models.ForeignKey(help_text='Membro autor do post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, help_text='Membros que curtiram o post', related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
